// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package leckermensa.domain.mensa;

import leckermensa.domain.mensa.Woche;

privileged aspect Woche_Roo_JavaBean {
    
    public String Woche.getMyname() {
        return this.Myname;
    }
    
    public void Woche.setMyname(String Myname) {
        this.Myname = Myname;
    }
    
}
