// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package leckermensa.domain.mensa;

import leckermensa.domain.mensa.Zutaten;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Zutaten_Roo_Configurable {
    
    declare @type: Zutaten: @Configurable;
    
}
